apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30800
    name: http
  - port: 443
    targetPort: 8080
    nodePort: 30443
    name: https
